### ISSUE TITLE
The current version of the object grasp accuracy is very low!

### ISSUE THREAD

**Issue by Vihe91** [jorgejgnz/HPTK#1]
InteractorController is supposed to judge that the mechanism is not accurate. Is there any solution?

**Comment by jorgejgnz** [comment]
Grab detection is performed by InteractorController, understanding grab as having simultaneous contacts between the grabbed object, at least one finger distal bone (excepting thumb) and a special collider (hand palm or thumb distal bone). At the moment I haven't found a lack of accuracy in grabbign detection.
What actions should be detected as grabbing and are not being detected with the current implementation?

**Comment by jorgejgnz** [comment]
Closing this issue due to not being active for more than one month
