### ISSUE TITLE
Unity XR Interaction Toolkit

### ISSUE THREAD

**Issue by alsharefee** [jorgejgnz/HPTK#10]
Hi, I was wondering if you have any plans to support Unity XR Interaction Toolkit?

Also, the documentation mention "DefaultSetup.UnityXR" but couldn't find it.

**Comment by jorgejgnz** [comment]
We had a closed issue for a similar problem: [Link to closed issue](https://github.com/jorgejgnz/HPTK/issues/8)
Are you're experiencing a similar problem? Did the given solution solve your problem?
