### ISSUE TITLE
Unity XR and Oculus Quest Hand Tracking

### ISSUE THREAD

**Issue by gabrieldevsouza** [jorgejgnz/HPTK#13]
I can't find any support or documentation explaingin how to implement the Oculus Quest Hand Tracking with Unity XR **without** the Oculus Integration asset.
I don't want to use the Oculus Integration Asset because it's a heavy dependency....
And I really wish to make builds to different headset models, not only Oculus...

**Comment by jorgejgnz** [comment]
Hi! Afaik UnityXR does not support finger tracking by itself (yet). You need Oculus Integration to get hand data from Quest.
