### ISSUE TITLE
Hi! Afaik UnityXR does not support finger tracking by itself (yet). You need Oculus Integration to get hand data from Quest.

### ISSUE THREAD

**Issue by MinervaVril** [jorgejgnz/HPTK#14]
Hi! Afaik UnityXR does not support finger tracking by itself (yet). You need Oculus Integration to get hand data from Quest.

_Originally posted by @jorgejgnz in https://github.com/jorgejgnz/HPTK/issues/13#issuecomment-966956849_

Hello!
I bought the HTPK asset (HPTK Posing & Snapping) and when I imported it, it has issue on the "DefaultSetup.UnityXR(missing prefabs)"

I am using Oculus quest 2.

can you guide me to the solution?
it will be very appreciated
thanks

**Comment by jorgejgnz** [comment]
Hi! DefaultSetup.UnityXR is a prefab included in the HPTK package. HPTK package might be missing in your project or it was not properly installed.

You can find a [setup guide](https://jorge-jgnz94.gitbook.io/hptk/setup) in HPTK documentation.
