### ISSUE TITLE
Hand model looks very bad

### ISSUE THREAD

**Issue by Kobe972** [jorgejgnz/HPTK#15]
I made a demo according to the official website https://jorge-jgnz94.gitbook.io/hptk/setup, but the hands in the scene are always incomplete.
![](http://home.ustc.edu.cn/~xuyichang/issues/HPTK.png)

**Comment by jorgejgnz** [comment]
Render queue is wrong on standard Skin_Master and Skin_Slave materials. Skin_Master should be 3000 (Transparent) and Skin_Slave should be 2000 (Geometry) so they don't overlap. I'll commit a fix for this issue

**Comment by jorgejgnz** [comment]
9ca954e076e61806a5f3e6f13f85e5876feb855b
