### ISSUE TITLE
HPTK Hand tracking with OpenXR 

### ISSUE THREAD

**Issue by PsyChonek** [jorgejgnz/HPTK#19]
Hello, I am unable to set up HPTK with OpenXR in Unity. 

Unity 2021.3.16f1
HPTK 0.6.6
HPTK Posing & Snapping 2.0.2

Target: Win(Vive)+Android(Quest)

I followed the guide for UnityXR and then tried steps from Issue #16 but no luck. 

Is there any guide that I can follow?

My current setup is 
![image](https://user-images.githubusercontent.com/45714777/212027219-9e4960b4-d8d9-4559-9ee4-23f38fec0037.png)

**Comment by jorgejgnz** [comment]
The hands does not follow your controllers or they do but they are offseted? Are you getting any error messages?

**Comment by jorgejgnz** [comment]
This issue has received no response and will be closed.
