### ISSUE TITLE
could you try to use VRTK and join the community to make it better?

### ISSUE THREAD

**Issue by studentutu** [jorgejgnz/HPTK#2]
I see that you are really enthusiastic about the VR, we need people like you to work on community projects like VRTK (VRTK 4 - Tilia/Zilia packages).
It is huge and really played nicely, but it lacks some of the core features and it would be great if someone like you could start on working on it.
Here is a quick link:
https://github.com/ExtendRealityLtd

Also, please joining the community on discord - all of the issues/dev/guides and so on are still under development and users can help each other there

**Comment by KellanHiggins** [comment]
I think you should keep doing what you are doing. VRKT is very very complex to try and implement and this seems to be more aligned with Oculus.

**Comment by studentutu** [comment]
I'm not one of the developers of the VRTK, I'm just the end-user, I just thought it would be nice to involve someone like yourself into it )
