### ISSUE TITLE
problem in script

### ISSUE THREAD

**Issue by PietKiekebos** [jorgejgnz/HPTK#5]
Assets\HPTK Posing & Snapping\HPTKExtensions\Snapping\Scripts\Modules\Snapper\SnapperController.cs(273,44): error CS0117: 'PhysHelpers' does not contain a definition for 'DoAfterUpdate'

**Comment by jorgejgnz** [comment]
The update for that fix was published a few hours ago. Please update and reimport [HPTK Posing & Snapping](https://assetstore.unity.com/packages/tools/utilities/hptk-posing-snapping-177933)
