### ISSUE TITLE
cant find DefaultAvatar

### ISSUE THREAD

**Issue by frere97** [jorgejgnz/HPTK#8]
i'm using the last version of hptk and cant find the DefaultAvatar

assets versions i'm using: 

htpk: 0.6.2
oculus XR plugin: 1.4.3
XR plugin management: 3.2.16

i'm following this tutorial: https://jorge-jgnz94.gitbook.io/hptk/setup/for-quest

**Comment by jorgejgnz** [comment]
Are you searching DefaultAvatar prefab within the Packages folder?

**Comment by frere97** [comment]
sorry, but i also do not have a package folder, just the one tha comes with the project and in the project, and there is only the manifest

**Comment by frere97** [comment]
the only thing i've have in my htpk folder is the integrations folder
![image](https://user-images.githubusercontent.com/35118366/128388019-ade02c5c-540b-4496-8c24-02f84d374b2a.png)

**Comment by jorgejgnz** [comment]
You can find a folder called Packages at the same level of the folder Assets. This folder contains files from all the installed packages in your project, including the HPTK package installed from Package Manager. Platform- or device-specific content is delivered inside integration packages that can only be extracted under Assets folder

![assetFolder](https://user-images.githubusercontent.com/60674219/128425920-608db031-0fa3-487d-8e33-69e0507f6ea0.PNG)

**Comment by frere97** [comment]
oooooooooooooooooooooow, thank u sir XD

**Comment by jorgejgnz** [comment]
You're welcome. I'll mark this issue as solved
