### ISSUE TITLE
use air link

### ISSUE THREAD

**Issue by frere97** [jorgejgnz/HPTK#9]
there is a way where i can use air link to test the game? build everytime i want to play make things very slow to develop

**Comment by jorgejgnz** [comment]
You can use Quest hand tracking in Unity Editor by setting the input data provider (IDP) called OVRInputSwitcher as `HPTK.leftEditorIdp` and `HPTK.rightEditorIdp` in the HPTK singleton. Input modules where `InputModel.inputDataProvider == null` will use their corresponding default IDPs referenced in HPTK singleton.

OVRInputSwitcher acts as intermediary between an IDP exclusive for hand tracking (OVRSkeletonTracker) and an IDP exclusive for controllers (UnityXRControllerTracker) so you can use hand trakcing or controllers. 

The following image shows the modifications needed in the HPTK singleton to be able to use hand tracking in Unity Editor (using Link).

![handtracking-in-editor](https://user-images.githubusercontent.com/60674219/128859772-e2dd2d74-de4d-4caf-b337-3be809330fca.PNG)

**Comment by frere97** [comment]
i've tried this, and still cant hit play and play in the editor, the camera don't recgonize my movements

**Comment by jorgejgnz** [comment]
Can you move your hands in PlayMode in a new scene using only OvrCameraRig and OvrHandPrefabs (without HPTK)?

**Comment by jorgejgnz** [comment]
This issue has received no response and will be closed.
